require 'paperclip'
require 'gb_paperclip/paperclip/attachment'
require 'gb_paperclip/paperclip/thumbnail'
require 'gb_paperclip/paperclip/pdf_thumbnail'
require 'gb_paperclip/paperclip/video_thumbnail'